mybatis:
  mapper-locations: classpath*:mapper/*.xml
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false